var datalink = [
    {
        id:1,
        name:"LINkman1",
        emailaddress:"LINkman1@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:2,
        name:"LINkman2",
        emailaddress:"LINkman2@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:3,
        name:"LINkman3",
        emailaddress:"LINkman3@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:4,
        name:"LINkman4",
        emailaddress:"LINkman4@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },

    {
        id:5,
        name:"LINkman5",
        emailaddress:"LINkman5@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:6,
        name:"LINkman6",
        emailaddress:"LINkman6@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    }
    ,{
        id:7,
        name:"LINkman7",
        emailaddress:"LINkman7@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },{
        id:8,
        name:"LINkman8",
        emailaddress:"LINkman8@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:9,
        name:"LINkman9",
        emailaddress:"LINkman9@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:10,
        name:"LINkman10",
        emailaddress:"LINkman10@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },

    {
        id:11,
        name:"LINkman11",
        emailaddress:"LINkman11@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    }
],
    recivedmessage = [
        {
            id:1,
            from:"linkman1",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:2,
            from:"linkman2",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:true
        },
        {
            id:3,
            from:"linkman3",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:4,
            from:"linkman4",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:5,
            from:"linkman5",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:6,
            from:"linkman6",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:7,
            from:"linkman7",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:8,
            from:"linkman8",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:9,
            from:"linkman9",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:10,
            from:"linkman10",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        }
    ],
    sendmessage = [
    {
        id:1,
        from:"linkman1",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"高仿是指根据仿制对象的原有外形",
        check:false
    },
    {
        id:2,
        from:"linkman2",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"从以上可以看出，国家的法律",
        check:true
    },
    {
        id:3,
        from:"linkman3",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"你说它黑，绝不可能是白的；",
        check:false
    },
    {
        id:4,
        from:"linkman4",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"这沙虽然轻盈，却看不清楚。",
        check:false
    },
    {
        id:5,
        from:"linkman5",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:" 回到上面说的，朋友他不能左右什么",
        check:false
    },
    {
        id:6,
        from:"linkman6",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"不做没把握的事儿，不说轻易说话",
        check:false
    },
    {
        id:7,
        from:"linkman7",
        date:21341543654675,
        theme:"在这时间里，有很多东西触碰到我",
        content:"how are you ?",
        check:false
    },
    {
        id:8,
        from:"linkman8",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"可能是从小就好强吧，我不喜欢失败。在一次次的成长中，我努力地汲取着知识的同时，总是在有意无意之间，把我与哥哥相比，一次一次的失败，又一次一次的爬起，一步一步的在人生路上打滚。之后，我上了大学，却发现自己的人生失去了目标，在人生的道路上有一道难以逾越的天堑。这不仅仅是我没考上自己理想的大学，没考上自己喜欢的专业，在自己的人生道路上迷茫，更是没有了动力。?",
        check:false
    },
    {
        id:9,
        from:"linkman9",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"今朝有酒今朝醉，人生得意须尽欢。人生就是一个字，累。就像我以前追赶我哥哥一样，一次的胜利能换来无尽的欢乐，一次的放荡能换来无尽的闲言啐语。以前的追赶，到现在家人的闲言啐语，让我的心如新竹似的豁裂了外箨，一次次地换来了新生，却又被人活生生的扼杀。想象别人一样快意恩仇，却又有太多的放不下。",
        check:false
    },
    {
        id:10,
        from:"linkman10",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"how are you ?",
        check:false
    }
];