var datalink = [
    {
        id:1,
        name:"LINkman1",
        emailaddress:"LINkman1@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:2,
        name:"LINkman2",
        emailaddress:"LINkman2@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:3,
        name:"LINkman3",
        emailaddress:"LINkman3@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:4,
        name:"LINkman4",
        emailaddress:"LINkman4@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },

    {
        id:5,
        name:"LINkman5",
        emailaddress:"LINkman5@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:6,
        name:"LINkman6",
        emailaddress:"LINkman6@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    }
    ,{
        id:7,
        name:"LINkman7",
        emailaddress:"LINkman7@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },{
        id:8,
        name:"LINkman8",
        emailaddress:"LINkman8@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:9,
        name:"LINkman9",
        emailaddress:"LINkman9@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },
    {
        id:10,
        name:"LINkman10",
        emailaddress:"LINkman10@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    },

    {
        id:11,
        name:"LINkman11",
        emailaddress:"LINkman11@sina.com",
        address:"bdsligvbuslvbdvckhz",
        phonenumber:"1234567890"
    }
],
    recivedmessage = [
        {
            id:1,
            from:"linkman1",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:2,
            from:"linkman2",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:true
        },
        {
            id:3,
            from:"linkman3",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:4,
            from:"linkman4",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:5,
            from:"linkman5",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:6,
            from:"linkman6",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:7,
            from:"linkman7",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:8,
            from:"linkman8",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:9,
            from:"linkman9",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        },
        {
            id:10,
            from:"linkman10",
            date:21341543654675,
            theme:"来自好友的问候",
            content:"how are you ?",
            check:false
        }
    ],
    sendmessage = [
    {
        id:1,
        from:"linkman1",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"高仿是指根据仿制对象的原有外形、材质、功能所仿制出来的仿冒品。也就是说这件物品不管工艺多么精湛，高仿度如何地高，都改变不了仿冒品的事实，更简单的说就是“装点”得足可以以假乱真的假货司法拍卖，即人民法院在民事案件强制执行程序中，按程序自行进行或委托拍卖公司公开处理债务人的财产，以清偿债权人债权。司法拍卖最基本的自然是要确定所拍卖的物品在法律规定之内，而高仿的LV包包显然是法律之外的产物。 ?",
        check:false
    },
    {
        id:2,
        from:"linkman2",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"从以上可以看出，国家的法律法规对销售假冒伪劣产品是有清晰、严格规定的，并不是已经告知就可以卖了，作为人民法院的工作人员，对此不可能不知情吧。高仿名画、高仿名包、未经检验的名酒等等，不但可能给竞拍者造成经济损失和健康风险，更是对名牌商标名誉的无形侵害。这起事件中，明显就存在侵害LV商标使用权人合法权益的嫌疑。法院加大执行力度，维系当事人权益的做法，值得我们敬重。但是，不能突破公序良俗，不能突破法律法规的底线。",
        check:true
    },
    {
        id:3,
        from:"linkman3",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"你说它黑，绝不可能是白的；相反，它如果会反驳，你可能会被它驳成黑，这个没人说得清楚。在贫困的家庭，在压抑的生活环境里，在充满敌意的工作中，在努力奋斗的时间里。我们有很多不满足，你或许顶不住这么多的不公平，走上很多条道路，偏左，偏右。我相信在这个世界环境里，有好人，肯定会有坏人。还有你不知道的是，可能坏人是被好人给逼出来的。这个就需要我和你一起冷静下来去思考了，看到坏人的时候，你并不知道他为什么会变成这样。说不定，另有苦衷。看到好人的时候，也不要相信她就是一个心地善良的人。电影电视剧看多了，你也会演戏。?",
        check:false
    },
    {
        id:4,
        from:"linkman4",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"这沙虽然轻盈，却看不清楚。朋友因为工作上的事情，和我分享了自己的心得。他说到了自私，被中枪！说道自私，只要是活着的人，都是自私的。可能你会说“好吧，但总有好坏！”其实，世上原本是没有“恶”人的，是这个世道把人逼成了“恶”人，或许，我是这样认为的。朋友说我“很现实”。这不能说是现实，只能说是看得多了，听到的多了，体会多了！这跟什么境界搭不上边，在这个复杂的社会里经历不一样而已。",
        check:false
    },
    {
        id:5,
        from:"linkman5",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:" 回到上面说的，朋友他不能左右什么，也无意改变什么。他能选择的，就是选择下一个人生站点。他说越来越不相信人了，是受到我的影响！“真小人，比伪君子更实在”他说“有什么就说，想做什么就做，你比有些朋友可靠的多，至少，你如果要在我背后放冷箭 你会先告诉我”。我还开玩笑的说“等我告诉他的时候，那就说明他已经中招了”。这个社会伪君子太多，面具太多，只能靠自己，把自己放在一个中间角色。我还会说“我就是一块牛皮糖，让你吃了，你感觉一般，但是，你又不想吐，因为它也甜。如果真非要吐出来，也得给你嘴里留下点神么。?",
        check:false
    },
    {
        id:6,
        from:"linkman6",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"不做没把握的事儿，不说轻易说话。之前是总是以为这是喜悦，后来人们给我上了生动的几堂课。现在要学的会变相引导，让和你对话的人跟着你走，说话的时候蒙上一层沙。谨言慎行有多重要，让你似懂非懂！有时候一点点细节被你放大后，效果会很好，还要会揣摩对方的心思。每个人都有是否的衡量标准，我也已经建立自己的衡量标准，你的观点可以影响到我的判断，但不可能左右我的判断。每个人的意见，我都会认真聆听，吸收适用的，剔除剩余的，保留有用的。我不是好人，我也不是什么坏人，该好的时候我会很好，不该好的时候，我也不会仁慈。受想行识，亦复如是。?",
        check:false
    },
    {
        id:7,
        from:"linkman7",
        date:21341543654675,
        theme:"在这时间里，有很多东西触碰到我，想也想不完，说也说不尽。我能做的只有把握自己的方向，跟着心走。顺着这点儿时间，接触那些碰到我的事物。或适应，或改变！不用去抱怨什么，用另一种方式找到它的平衡点，抱怨只能让你身边的人或事更糟糕。一切没有没有好坏，思想使然，一切改变，由你开始！",
        content:"how are you ?",
        check:false
    },
    {
        id:8,
        from:"linkman8",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"可能是从小就好强吧，我不喜欢失败。在一次次的成长中，我努力地汲取着知识的同时，总是在有意无意之间，把我与哥哥相比，一次一次的失败，又一次一次的爬起，一步一步的在人生路上打滚。之后，我上了大学，却发现自己的人生失去了目标，在人生的道路上有一道难以逾越的天堑。这不仅仅是我没考上自己理想的大学，没考上自己喜欢的专业，在自己的人生道路上迷茫，更是没有了动力。?",
        check:false
    },
    {
        id:9,
        from:"linkman9",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"今朝有酒今朝醉，人生得意须尽欢。人生就是一个字，累。就像我以前追赶我哥哥一样，一次的胜利能换来无尽的欢乐，一次的放荡能换来无尽的闲言啐语。以前的追赶，到现在家人的闲言啐语，让我的心如新竹似的豁裂了外箨，一次次地换来了新生，却又被人活生生的扼杀。想象别人一样快意恩仇，却又有太多的放不下。",
        check:false
    },
    {
        id:10,
        from:"linkman10",
        date:21341543654675,
        theme:"送去远方的祝福",
        content:"how are you ?",
        check:false
    }
];